//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebshopManagementEntities : DbContext
    {
        public WebshopManagementEntities()
            : base("name=WebshopManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ProductCategory> tbl_ProductCategory { get; set; }
        public virtual DbSet<tbl_ProductStock> tbl_ProductStock { get; set; }
        public virtual DbSet<tbl_Purchase> tbl_Purchase { get; set; }
        public virtual DbSet<tbl_Sale> tbl_Sale { get; set; }
        public virtual DbSet<tbl_CustomerInfo> tbl_CustomerInfo { get; set; }
        public virtual DbSet<tbl_ProductSubcategory> tbl_ProductSubcategory { get; set; }
        public virtual DbSet<tbl_UnsignCustomer> tbl_UnsignCustomer { get; set; }
        public virtual DbSet<tbl_ProductBrand> tbl_ProductBrand { get; set; }
        public virtual DbSet<tbl_Cart> tbl_Cart { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_ProductInfo> tbl_ProductInfo { get; set; }
    }
}
