//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int Order_Id { get; set; }
        public string Session_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Address { get; set; }
        public string Order_Price { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
    }
}
